In [3]:
import pandas as pd

era_df = pd.read_csv('exploring-data/era5-germany-july-september-2022.csv')

In [4]:
era_df.sample(5)

,valid_time,latitude,longitude,u10,v10,t2m,tcc,tp,ssrd
1835,2022-09-15 12:00:00,51.0,10.0,3.482239,-1.671082,15.065887,1.000000,0.000000,299072.0
247,2022-07-11 08:00:00,51.0,10.0,1.817352,-2.635147,14.837311,0.999512,0.000000,639488.0
1384,2022-08-27 17:00:00,51.0,10.0,0.870285,-4.000687,19.001984,0.999756,0.000000,0.0
1012,2022-08-12 05:00:00,51.0,10.0,-1.569824,-0.511475,14.005524,0.198029,0.000000,109312.0
1796,2022-09-13 21:00:00,51.0,10.0,2.345886,1.335693,17.835480,1.000000,0.000436,0.0

In [5]:
era_df = era_df.rename(columns={'valid_time': 'Datetime (UTC)'})

In [6]:
era_df.sample()

,Datetime (UTC),latitude,longitude,u10,v10,t2m,tcc,tp,ssrd
1848,2022-09-16 01:00:00,51.0,10.0,3.664291,-0.255402,10.574982,0.93927,0.0,0.0

In [7]:
era_df = era_df.drop(columns=['latitude', 'longitude'])

In [8]:
era_df.sample()

,Datetime (UTC),u10,v10,t2m,tcc,tp,ssrd
725,2022-07-31 06:00:00,0.704666,1.198029,16.031464,0.645752,0.0,381824.0

In [9]:
era_df.isnull().sum()

Datetime (UTC)    0
u10               0
v10               0
t2m               0
tcc               0
tp                0
ssrd              0
dtype: int64

In [10]:
price_df = pd.read_csv('exploring-data/electricity-price-july-september-2022.csv')

In [11]:
price_df.sample(5)

,Country,ISO3 Code,Datetime (UTC),Datetime (Local),Price (EUR/MWhe)
156,Germany,DEU,2022-07-07 12:00:00,2022-07-07 14:00:00,158.20
1416,Germany,DEU,2022-08-29 00:00:00,2022-08-29 02:00:00,500.98
1433,Germany,DEU,2022-08-29 17:00:00,2022-08-29 19:00:00,867.85
657,Germany,DEU,2022-07-28 09:00:00,2022-07-28 11:00:00,440.53
2076,Germany,DEU,2022-09-25 12:00:00,2022-09-25 14:00:00,221.68

In [12]:
price_df = price_df.rename(columns={'valid_time': 'Datetime (UTC)'})

In [13]:
price_df.isnull().sum()

Country             0
ISO3 Code           0
Datetime (UTC)      0
Datetime (Local)    0
Price (EUR/MWhe)    0
dtype: int64

In [14]:
price_df = price_df.drop(columns=['Datetime (Local)', 'ISO3 Code'])
price_df.sample()

      Country       Datetime (UTC)  Price (EUR/MWhe)
1827  Germany  2022-09-15 03:00:00            322.99

In [15]:
pvgis_df = pd.read_csv('exploring-data/pvgis-germany-2022.csv')

In [16]:
pvgis_df.sample(5)

               time       P   G(i)  H_sun    T2m  WS10m  Int
3582  20220530:0610  259.48  318.0  25.05   7.62   1.59  0.0
2587  20220418:1910    0.00    0.0   0.00   9.42   1.79  0.0
8228  20221209:2010    0.00    0.0   0.00  -0.33   1.66  0.0
4677  20220714:2110    0.00    0.0   0.00  16.87   2.69  0.0
7753  20221120:0110    0.00    0.0   0.00  -4.43   0.55  0.0

In [17]:
pvgis_df = pvgis_df.rename(columns={'time': 'Datetime (UTC)'})

In [18]:
pvgis_df = pvgis_df.drop(columns=['Int'])

In [19]:
pvgis_df.sample()

     Datetime (UTC)    P  G(i)  H_sun   T2m  WS10m
2905  20220502:0110  0.0   0.0    0.0  7.57   1.93

In [20]:
pvgis_df['Datetime (UTC)'] = pd.to_datetime(
    pvgis_df['Datetime (UTC)'].astype(str),
    format='%Y%m%d:%H%M'
)

In [21]:
pvgis_df

          Datetime (UTC)    P  G(i)  H_sun    T2m  WS10m
0    2022-01-01 00:10:00  0.0   0.0    0.0  10.18   3.72
1    2022-01-01 01:10:00  0.0   0.0    0.0  10.07   3.38
2    2022-01-01 02:10:00  0.0   0.0    0.0   9.98   2.97
3    2022-01-01 03:10:00  0.0   0.0    0.0   9.88   2.76
4    2022-01-01 04:10:00  0.0   0.0    0.0   9.76   2.90
...                  ...  ...   ...    ...    ...    ...
8755 2022-12-31 19:10:00  0.0   0.0    0.0  13.32   5.52
8756 2022-12-31 20:10:00  0.0   0.0    0.0  13.36   5.72
8757 2022-12-31 21:10:00  0.0   0.0    0.0  13.36   5.93
8758 2022-12-31 22:10:00  0.0   0.0    0.0  13.36   6.00
8759 2022-12-31 23:10:00  0.0   0.0    0.0  13.24   5.93

[8760 rows x 6 columns]

In [22]:
era_df

,Datetime (UTC),u10,v10,t2m,tcc,tp,ssrd
0,2022-07-01 01:00:00,2.669998,-0.490677,18.401154,1.000000,0.000174,0.0
1,2022-07-01 02:00:00,5.843552,0.322693,16.314117,1.000000,0.000242,0.0
2,2022-07-01 03:00:00,4.419983,-1.093002,14.973541,1.000000,0.000000,0.0
3,2022-07-01 04:00:00,1.841629,-2.487869,14.196320,1.000000,0.000000,22464.0
4,2022-07-01 05:00:00,1.882843,-1.151215,13.689545,0.998505,0.000624,57600.0
...,...,...,...,...,...,...,...
2202,2022-09-30 19:00:00,0.431381,2.671600,8.399506,0.281250,0.000000,0.0
2203,2022-09-30 20:00:00,0.714874,2.838486,7.761444,0.010498,0.000000,0.0
2204,2022-09-30 21:00:00,0.971848,2.612183,7.278046,0.011993,0.000000,0.0
2205,2022-09-30 22:00:00,1.020859,3.566208,7.417389,1.000000,0.000000,0.0
2206,2022-09-30 23:00:00,0.894058,3.763351,7.708160,1.000000,0.000000,0.0

In [23]:
era_df['Datetime (UTC)'] = pd.to_datetime(era_df['Datetime (UTC)'])
price_df['Datetime (UTC)'] = pd.to_datetime(price_df['Datetime (UTC)'])
pvgis_df['Datetime (UTC)'] = pd.to_datetime(pvgis_df['Datetime (UTC)'])

pvgis_df['Datetime (UTC)'] = pvgis_df['Datetime (UTC)'].dt.floor('h')

print('era_df sample:', era_df['Datetime (UTC)'].iloc[0])
print('price_df sample:', price_df['Datetime (UTC)'].iloc[0])
print('pvgis_df sample:', pvgis_df['Datetime (UTC)'].iloc[0])

era_df sample: 2022-07-01 01:00:00
price_df sample: 2022-07-01 00:00:00
pvgis_df sample: 2022-01-01 00:00:00

In [29]:
merged = pd.merge(era_df, price_df, on='Datetime (UTC)', how='inner')
print('era + price shape:', merged.shape)

final_df = pd.merge(merged, pvgis_df, on='Datetime (UTC)', how='inner')
final_df.shape
final_df.head()

era + price shape: (2207, 9)

,Datetime (UTC),u10,v10,t2m,tcc,tp,ssrd,Country,Price (EUR/MWhe),P,G(i),H_sun,T2m,WS10m
0,2022-07-01 01:00:00,2.669998,-0.490677,18.401154,1.000000,0.000174,0.0,Germany,259.62,0.00,0.0,0.00,19.24,3.72
1,2022-07-01 02:00:00,5.843552,0.322693,16.314117,1.000000,0.000242,0.0,Germany,259.64,0.00,0.0,0.00,17.75,3.59
2,2022-07-01 03:00:00,4.419983,-1.093002,14.973541,1.000000,0.000000,0.0,Germany,270.50,0.00,0.0,0.00,16.43,3.03
3,2022-07-01 04:00:00,1.841629,-2.487869,14.196320,1.000000,0.000000,22464.0,Germany,339.78,0.48,7.0,7.16,15.47,2.76
4,2022-07-01 05:00:00,1.882843,-1.151215,13.689545,0.998505,0.000624,57600.0,Germany,378.23,6.96,19.0,15.85,14.57,2.55