In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/raw/prices-raw.csv')

In [4]:
df.head()

,Country,ISO3 Code,Datetime (UTC),Datetime (Local),Price (EUR/MWhe)
0,Germany,DEU,2015-01-01 00:00:00,2015-01-01 01:00:00,22.34
1,Germany,DEU,2015-01-01 01:00:00,2015-01-01 02:00:00,22.34
2,Germany,DEU,2015-01-01 02:00:00,2015-01-01 03:00:00,22.34
3,Germany,DEU,2015-01-01 03:00:00,2015-01-01 04:00:00,22.34
4,Germany,DEU,2015-01-01 04:00:00,2015-01-01 05:00:00,22.34

In [5]:
df.describe()

       Price (EUR/MWhe)
count     100940.000000
mean          74.105536
std           79.707527
min         -372.420000
25%           30.740000
50%           46.680000
75%           94.602500
max          867.850000

In [6]:
df.isna().sum()

Country             0
ISO3 Code           0
Datetime (UTC)      0
Datetime (Local)    0
Price (EUR/MWhe)    0
dtype: int64

In [7]:
df = df.drop(columns=['ISO3 Code', 'Datetime (Local)'])

In [8]:
df.sample()

       Country       Datetime (UTC)  Price (EUR/MWhe)
37073  Germany  2019-03-25 17:00:00              39.6

In [9]:
df.to_csv('price.csv', index=False)