In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('../data/raw/meteo-raw.csv')

In [24]:
df.head()

,time,temperature_2m,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,precipitation
0,2023-07-01T00:00,10.5,4.3,265,48,0.0,0.0
1,2023-07-01T01:00,10.4,2.5,188,53,0.0,0.0
2,2023-07-01T02:00,8.9,3.1,159,100,0.0,0.0
3,2023-07-01T03:00,9.0,3.4,162,100,0.0,0.0
4,2023-07-01T04:00,9.7,4.0,153,100,9.0,0.0

In [25]:
df = df.rename(columns={'time': 'Datetime (UTC)'})

In [26]:
df.columns

Index(['Datetime (UTC)', 'temperature_2m', 'wind_speed_10m',
       'wind_direction_10m', 'cloud_cover', 'shortwave_radiation',
       'precipitation'],
      dtype='object')

In [27]:
df.isna().sum()

Datetime (UTC)         0
temperature_2m         0
wind_speed_10m         0
wind_direction_10m     0
cloud_cover            0
shortwave_radiation    0
precipitation          0
dtype: int64

In [28]:
df['Datetime (UTC)'].sample()

1585    2023-09-05T01:00
Name: Datetime (UTC), dtype: object

In [29]:
df['Datetime (UTC)'] = df['Datetime (UTC)'].str.replace(
    r'(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})',
    r'\1-\2-\3 \4:\5',
    regex=True
)

In [30]:
df['Datetime (UTC)'].sample()

2123    2023-09-27 11:00
Name: Datetime (UTC), dtype: object

In [31]:
df['Datetime (UTC)'] = pd.to_datetime(df['Datetime (UTC)'])

In [32]:
df.sample()

,Datetime (UTC),temperature_2m,wind_speed_10m,wind_direction_10m,cloud_cover,shortwave_radiation,precipitation
1317,2023-08-24 21:00:00,20.8,2.9,277,100,0.0,0.1

In [33]:
df.to_csv('meteo.csv', index=False)